### ISSUE TITLE
Display problems with the Search function

### ISSUE THREAD

**Issue by Gabriele69** [ubports/messaging-app#2] opened 2017-06-08 08:44 UTC
Hi to all.
I use my Acquaris 4.5 (Legacy 15.04 Ubports r 8).
The problem occurs when you start the message application and try to search for a message by using the search bar at the top.
Beginning to type characters, the view becomes compact and distorts.

Step to reproduce the error:
1. Make sure you have at least some message in the list (sent or received) of the application;
2. Start the message application;
3. Click the lens on the top right to activate the search bar;
4. Try typing something

GM

**Comment by Flohack74** [comment] 2017-06-08 17:53
Confirmed on E4.5 and E5... :)

**Comment by mihaelmilea** [comment] 2017-08-25 20:05
I can confirm it on Pro 5. The names of people are scrambled as results of search in text messages.

**Comment by Daniel20000522** [comment] 2018-04-04 14:38
Confirmed on Nexus 5 (Ubports 15.04 RC r24).

**Comment by jezek** [comment] 2018-04-18 20:57
Confirmed on FP2

**Comment by Nativeworld** [comment] 2018-08-17 09:56
Confirmed on Nexus 5 and OPO with 15.04

**Comment by advocatux** [comment] 2018-08-17 10:05
This issue is still happening in xenial.

Confirmed on a BQ E4.5 (krillin) running Ubuntu 16.04 (2018-08-17).

**Comment by lduboeuf** [comment] 2018-09-14 10:59
should we close this issue now that @kugiigi PR is accepted ? Big thank you for resolving that long lasting bug :)

**Comment by Flohack74** [comment] 2018-09-14 17:07
To me its not fully fixed: Now after searching one time, it wont work anymore. You enter smth, but then immediately the search field disappears again...

**Comment by kugiigi** [comment] 2018-09-14 20:07
Not sure what you encounter but I just tried it again on mine and it does work fine albeit really slow when there's too many data. Maybe you are hiding the OSK? that stops the search.

**Comment by Gabriele69** [comment] 2019-02-04 10:58
Hi, 
Now my phone (Aquaris E4.5 on RC 16.04 W05) works fine.
The error has disappeared

G

**Comment by Daniel20000522** [comment] 2019-02-04 11:41
My Nexus 5 RC 2019-W5 also works fine.

**Comment by jezek** [comment] 2019-02-04 14:46
on FP2 this error is no more

**Comment by lduboeuf** [comment] 2019-02-12 21:05
for me as well on Nexus 5. Thank you for fixing it, so old bug :)

**Comment by UniversalSuperBox** [comment] 2019-02-12 21:05
Works for me

**Closed by UniversalSuperBox** 2019-02-12 21:05 UTC
Labels: bug
