### ISSUE TITLE
Incomplete SMS

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#72] opened 2019-01-24 09:30 UTC
Sometimes, with (only) one of my penpal, the SMS is incomplete. I got only the very end!
Her SMS is not too long and there is no picture associated.
That is very very annoying. Even if she send it twice, there is the same problem.

I have a Nexus 4 with OTA-7 (same with OTA-5 and 6)

**Comment by UniversalSuperBox** [comment] 2019-02-12 17:41
Duplicate of ubuntu-touch#1023

Please only report issues in one place at a time. If you would like a report moved, please ask us.

**Comment by UniversalSuperBox** [comment] 2019-02-12 17:42
Sorry, this sounds more like https://github.com/ubports/ubuntu-touch/issues/1022

**Closed by UniversalSuperBox** 2019-02-12 17:41 UTC
