### ISSUE TITLE
Animated gif support

### ISSUE THREAD

**Issue by parksjr** [ubports/messaging-app#123] opened 2019-08-19 18:32 UTC
**Expected behavior:**
Animated gifs sent via text mms should animate

**Actual behavior:**
Gif does not animate.

**Steps to reproduce:**
Send animated gif from any phone to your ubuntu phone via text.

**Device Information**
Device: Nexus 5
Channel: Development
Release: 2019-08-17

**more blab**
Probably classified as an enhancement. Certainly not a show stopper, but is a nice-to-have. Android and iPhone users alike have integrated gif reaction built into keyboards and messaging apps, and gif reactions has become a culturally significant form of communication in the past few years at least.

**Comment by lduboeuf** [comment] 2020-09-09 21:17
So i gave a try, but sadly it lands nowhere.
MMS gifs are not stored as gif,  there is things to do at a lower level or i didn't find how

**Comment by Intrinsically-Sublime** [comment] 2020-12-01 07:17
I have been looking into this and the gifs are coming through as animated gifs and they are being saved as animated gifs. If you click on the still picture in the message it will open in a preview. If you then click the download button, select gallery and it will be saved in /home/phablet/pictures/imported/ if you go to that location via the file browser, click and select preview it will show you a working animated gif. But if you open it in gallery it is not animated.

I found an issue on gitlab for the Gallery App involving animated gifs.
https://gitlab.com/ubports/apps/gallery-app/-/issues/41
He appears to have a branch specifically for animated gifs that apparently works. I am not sure if it has ever been merged with the mainline of Gallery though.
https://gitlab.com/StefWe/gallery-app/-/tree/animatedGif

I am only a few days into using Ubuntu touch on an OPO and the code is all really foreign to me as well as not being a good programmer especially with object oriented stuff so I do not think I will be able to solve the issue myself. I do not have a build environment set up for Ubuntu touch so I can not test if the above Gallery fix solves the MMS Gif issue.

**Comment by lduboeuf** [comment] 2020-12-01 08:13
Oh so my tests were wrong, ;-), need to give one day another try. thanks for reporting
Edit: So my test were wrong since the old Android phone i've used for the test send MMS gif as a single frame image.

**Comment by Intrinsically-Sublime** [comment] 2020-12-08 21:04
I am glad to see you got something figured out to make this work. I am not in a hurry but I am curious when we will see the app get this update? Do you have any idea how long it will take for it make it into an update?

**Comment by lduboeuf** [comment] 2020-12-08 21:09
This should be for next OTA-16 if no regressions found.
If you are on devel it is already testable, just do `sudo ubports-qa install messaging-app 258`

**Comment by lduboeuf** [comment] 2020-12-08 21:47
~~Still need to work with webm format~~

**Comment by Flohack74** [comment] 2021-01-12 17:10
Cannot be bug and enhancement at the same time. We started review on that, should probably come in the next update ;)

**Comment by lduboeuf** [comment] 2021-01-19 22:31
Anybody can test please, especially the autoplay, scroll, play/pause, image view, settings.
Don't need to send effective MMS, just send gifs or webp images to yourself with data off.
Only tested on BQ4.5

**Comment by Intrinsically-Sublime** [comment] 2021-01-21 09:47
Is there a way to test this on the release candidate?

**Comment by lduboeuf** [comment] 2021-01-21 09:53
> Is there a way to test this on the release candidate?

Apart from pulling the PR and build yourself with clickable, i am not sure it is recommended

**Comment by FlavioMala** [comment] 2021-01-22 22:55
Just yesterday I received a gif via email..... To see the animation after various tests at the end (at the moment) I solved it by installing gThumb via Libertine.
[BQ E5, ch dev]

**Comment by lduboeuf** [comment] 2021-01-22 23:04
> Just yesterday I received a gif via email..... To see the animation after various tests at the end (at the moment) I solved it by installing gThumb via Libertine.
> [BQ E5, ch dev]

And what about messaging-app ? Have tested the PR ?

**Comment by FlavioMala** [comment] 2021-01-23 10:39
Not yet (I have not activated the MMS service), but now when I open the image "in autoload", the animation works:
![screenshot20210123_113011152](https://user-images.githubusercontent.com/50835740/105575829-cd795a00-5d6e-11eb-9571-32cdfe9f3b36.png)
Result ("moving"):
![screenshot20210123_113344039](https://user-images.githubusercontent.com/50835740/105575908-6e681500-5d6f-11eb-91be-0ef446e02579.png)

[Here the animate "hippo" gif:
![ippopotamo-immagine-animata-0099](https://user-images.githubusercontent.com/50835740/105575917-86d82f80-5d6f-11eb-9806-60a94b0e6afd.gif)
]

**Comment by lduboeuf** [comment] 2021-01-23 10:42
but what you are showing isn't messaging-app, nothing to do with this issue and PR i would say

**Comment by FlavioMala** [comment] 2021-01-23 11:56
Yes, right... a little OT, but the problem is also with "Gallery"

**Comment by FlavioMala** [comment] 2021-01-23 13:12
At the end.. +- tested.
The problem is the big white space (in all messages!):
![screenshot20210123_140708790](https://user-images.githubusercontent.com/50835740/105579134-da08ad00-5d84-11eb-889e-022aecae1518.png)
It is very hard to scroll up (need to keep holding the finger on screen...)

**Comment by FlavioMala** [comment] 2021-01-23 13:19
This is a normal sms (received), with text (short text) totally under the imput window (need scroll up, keeping finger on screen, viceversa it return down):
![screenshot20210123_141238985](https://user-images.githubusercontent.com/50835740/105579338-36200100-5d86-11eb-9695-6759ab1043bd.png)

**Comment by FlavioMala** [comment] 2021-01-23 13:28
...another screenshot (sms, a lot of text):
![screenshot20210123_142434754](https://user-images.githubusercontent.com/50835740/105579482-45ec1500-5d87-11eb-9a61-467ef67f1d83.png)

**Comment by lduboeuf** [comment] 2021-01-23 14:53
> At the end.. +- tested.
> The problem is the big white space (in all messages!):
> ![screenshot20210123_140708790](https://user-images.githubusercontent.com/50835740/105579134-da08ad00-5d84-11eb-889e-022aecae1518.png)
> It is very hard to scroll up (need to keep holding the finger on screen...)

humm, so you've tested the PR on devel?. I used to have that also a long time ago,, but it was due to something that went bad with ubports-qa.

**Comment by lduboeuf** [comment] 2021-01-23 15:08
hymm confirmed, ubports-qa is broken or maybe this PR need to be built again.

**Comment by FlavioMala** [comment] 2021-01-23 16:19
BQ E5, channel Devel, release 650 (update today).
NB animation works! Only the "layout" is abnormal.
...and this is what happens now with multiple messages (hope useful):
![screenshot20210123_171156246](https://user-images.githubusercontent.com/50835740/105607491-57411b80-5d9f-11eb-8ad7-bcf20ef356c6.png)

**Comment by lduboeuf** [comment] 2021-01-23 17:58
i've rebuilt messaging-app PR #258, now it don't ask me to remove or change whatever dependencies, only messaging-app.
there is still the layout issue ( i don't have the same as you, but i have empty bubbles ) but it is not related to that PR.

**Closed as completed** 2021-01-23 18:17 UTC
Labels: enhancement

**Comment by FlavioMala** [comment] 2021-01-23 20:50
In my BQ now (again sudo ubports-qa install messaging-app 258) the layout is OK... and "hippo" (sms/mms) is moving!
Thank you very much!

**Comment by Intrinsically-Sublime** [comment] 2021-02-24 20:29
I just tested this on the release channel and on my carrier with mobile data on (It is always enabled) if someone sends me a GIF I do not receive it. And after that I do not receive any SMS or MMS messages for ten minutes after. Even after switching back to stable it still took ten minutes to get the messages and the pictures did show up eventually on stable that were sent while on RC. I can only guess it sends something to the network that cause the network to delay sending messages until the GIF has either been received or failed.

**Comment by lduboeuf** [comment] 2021-02-24 20:33
humm i think it is a different issue, on which device are you ?

**Comment by Intrinsically-Sublime** [comment] 2021-02-24 23:44
~~Sorry should have said that again. I am using a OnePlus One Bacon as a daily driver. I switched back to stable right away because SMS and MMS are the only reason I have a phone and I need them working. If there is some way I can help I am willing to switch back to RC to test. (I reinstalled all apps after updating)~~

~~EDIT: I should also say that after returning to stable and finally receiving the GIFs that had been sent to me while I was on RC everything is working as it was before. I get (non-animated) pictures and SMS messages nearly instantly.~~

**Comment by Intrinsically-Sublime** [comment] 2021-02-25 06:58
I had some spare time and decided to try the RC channel and this time things are working as they should with animation too.

**Comment by Intrinsically-Sublime** [comment] 2021-03-15 00:22
I tried the RC channel again today and all animated images I receive are animated but I can no longer send animated GIFs. It sends a single frame. I resinstalled all apps via the update menu, that did not help. I restated 5 times (3 pwr off, pwr on)(2 reboots) and I still can not send animated GIFs. I then rolled back to OTA 15 and still have the issue after a few restarts. Also while on the RC channel in the messaging app I could not backspace to a word to change it's suggested correction, on OTA-15 it still works.

**Comment by lduboeuf** [comment] 2021-03-15 09:51
> I tried the RC channel again today and all animated images I receive are animated but I can no longer send animated GIFs. It sends a single frame

humm can't reproduce here, need confirmation 

>Also while on the RC channel in the messaging app I could not backspace to a word to change it's suggested correction, on OTA-15 it still works.

That is not related to this feature, please fill a bug for that case
