### ISSUE TITLE
Conversation view will show a phone number not your contact's name

### ISSUE THREAD

**Issue by SaltyCybernaut** [ubports/messaging-app#77] opened 2019-02-19 06:51 UTC
In the conversation view of the messaging app the phone number of your contact will be displayed at the top of the screen instead of the name of your contact. This is inconsistent with the overview page which will show your contact's name.

* Device: Nexus 5 - hammerhead
* Channel: stable
* Release: OTA-7

**Comment by krille-chan** [comment] 2019-03-12 17:38
I can confirm this **sometimes** on Nexus 5. But I'm not sure how to reproduce it. Also sometimes the phone number disappears and the contact name is visible.

Is there anyone currently affected by this bug and knows steps how to reproduce this?

**Comment by Punkette** [comment] 2019-03-12 19:27
Just open one conversation with one of your contact. If you send a message to him (her), his (her) name is replaced by the phone number into the header as long as you don't close the conversation

I'm using a MX4 RC channel

**Comment by SaltyCybernaut** [comment] 2019-03-14 16:58
After further testing, it will either show the phone number for all messages or it will show the contact's name for all messages. I cannot predict when it will choose to display contact names or phone numbers.

**Comment by krille-chan** [comment] 2019-03-27 13:22
I have a fix for this but this could need more testers: https://github.com/ubports/messaging-app/pull/87

**Comment by krille-chan** [comment] 2019-05-24 14:41
Should be fixed now in the next devel/rc builds. I'll wait for confirmation to close this issue here...

**Comment by StefWe** [comment] 2019-06-05 08:14
I couldn't reproduce the problem anymore with the change.
Tested on MX4

**Comment by UniversalSuperBox** [comment] 2019-06-19 22:35
Fixed by https://github.com/ubports/messaging-app/pull/87

**Closed as completed by UniversalSuperBox** 2019-06-19 22:35 UTC
Labels: enhancement, help wanted

**Comment by jezek** [comment] 2019-08-10 12:35
FP2 (2019-W32) - Fixed.

In messaging app, in conversation view, there is proper contact name in the top bar instead of phone number.
