### ISSUE TITLE
Keyboard disable

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#67] opened 2018-12-13 14:17 UTC
From time to time, when I open a conversation the keyboard disappear.
I have to quit then go back to the messaging app to see it again

(LGE Nexus 4, OTA-5 and OTA-6)

**Comment by SaltyCybernaut** [comment] 2019-02-19 06:17
I experience a similar issue using a Nexus 5 (hammerhead) on 16.04(OTA-7). It will sometimes happen when I am in the conversation view of the messaging app, I then switch to a different app, then switch back and when I select the text box the keyboard will not activate. I will then have to close the app to resolve the issue.

**Comment by krille-chan** [comment] 2019-03-12 17:44
I can confirm this but I have similar issues on other apps like Telegram or FluffyChat. I would assume that this bug is related to the OSK or maybe the Ubuntu UI Toolkit and not to the messages app. Can you confirm, that the bug affects other messaging apps on your phone too?

**Comment by Thieb67k** [comment] 2019-03-13 06:42
Actually, I have never tried another messaging app... I would say that is due only to the OSK (?).

**Comment by abkro** [comment] 2019-05-20 19:56
I experience this issue frequently on my Nexus 5, now running 2019-W20 (channel rc). 

A couple of days ago an interesting thing happened: I was starting to compose a message. As I was typing the second or third word, the keyboard disappeared. I went back to the main view and reentered the message thread to start typing once more. The exact same thing happened _on_the_same_character_ ! This repeated itself once more before I tried rewording the message. That solved the problem and I was able to complete the message.

**Comment by krille-chan** [comment] 2019-05-21 04:44
> I experience this issue frequently on my Nexus 5, now running 2019-W20 (channel rc).
> 
> A couple of days ago an interesting thing happened: I was starting to compose a message. As I was typing the second or third word, the keyboard disappeared. I went back to the main view and reentered the message thread to start typing once more. The exact same thing happened _on_the_same_character_ ! This repeated itself once more before I tried rewording the message. That solved the problem and I was able to complete the message.

This bug is in all apps. That's not related to the messages app...

**Comment by ghost** [comment] 2019-08-08 03:11
I can confirm this bug is also affecting the Oneplus One (Oneplus Bacon, stable channel OTA-7, OTA-8, OTA-9, UBports current build description: UBuntu 16.04 LTS - armhf (20190427)). I have found that pulling down the notification drawer and releasing it will most of the time prompt the keyboard to come back up. Has anyone heard of any potential permanent fixes for this bug?

**Comment by lduboeuf** [comment] 2020-01-03 07:53
follow up here: https://github.com/ubports/ubuntu-touch/issues/1268

**Comment by lduboeuf** [comment] 2020-02-09 22:00
this bug seems to be fixed now on devel, can we close that issue ?

**Comment by Flohack74** [comment] 2020-02-10 15:40
Lets keep it open until RC is out on Wed. I can see from my point of view that we need more testers on it.

**Comment by lduboeuf** [comment] 2020-07-07 08:44
haven't experienced that issue since a while

**Comment by Thieb67k** [comment] 2020-07-07 09:04
Actually, neither have I. Shall we close it?

**Comment by lduboeuf** [comment] 2020-07-07 09:06
> Actually, neither have I. Shall we close it?

yes please, ( i can't ) :)

**Closed** 2020-07-07 09:09 UTC
